export const API_URL = 'http://raspberrysky.hopto.org:4000';

export const HOURLY_FIELDS = [
    'AVG_AMBIENT_TEMPERATURE',
    'MIN_AMBIENT_TEMPERATURE',
    'MAX_AMBIENT_TEMPERATURE',
    'AVG_GROUND_TEMPERATURE',
    'MIN_GROUND_TEMPERATURE',
    'MAX_GROUND_TEMPERATURE',
    'AVG_AIR_PRESSURE',
    'AVG_HUMIDITY',
    'AVG_WIND_DIRECTION',
    'AVG_WIND_SPEED',
    'MAX_WIND_GUST_SPEED',
    'AVG_WIND_CHILL',
    'MIN_WIND_CHILL',
    'AVG_HEAT_IDX',
    'MAX_HEAT_IDX',
    'AVG_DEW_PT',
    'MIN_DEW_PT',
    'MAX_DEW_PT',
    'TOTAL_RAINFALL',
    'MAX_CPU_TEMP'
];

export const DAILY_FIELDS = [
    "AMBIENT_TEMPERATURE",
    "GROUND_TEMPERATURE",
    "AIR_PRESSURE",
    "HUMIDITY",
    "WIND_DIRECTION",
    "WIND_SPEED",
    "WIND_GUST_SPEED",
    "WIND_CHILL",
    "HEAT_IDX",
    "DEW_PT",
    "CPU_TEMP",
    "RAINFALL"
];